export interface SkillDefinition {
  skillId: string;
  name: string;
  description: string;
  maxLevel: number;
  prerequisiteSkillId: string;
  prerequisiteLevel: number;
  prerequisitePlayerLevel: number;
  costSkillPoints: number;
  positionX: number;
  positionY: number;
  sortOrder: number;
}

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  {
    skillId: 'scavenge_multiplier',
    name: 'Scavenge Multiplier',
    description: '+25% per level to Scavenge yield.',
    maxLevel: 4,
    prerequisiteSkillId: '',
    prerequisiteLevel: 0,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 0,
    positionY: 0,
    sortOrder: 0,
  },
  {
    skillId: 'unlock_shelter',
    name: 'Unlock Shelter',
    description: 'Unlocks the Build Shelter activity in the Wastes.',
    maxLevel: 1,
    prerequisiteSkillId: 'scavenge_multiplier',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 220,
    positionY: 0,
    sortOrder: 1,
  },
  {
    skillId: 'unlock_parts',
    name: 'Unlock Parts',
    description: 'Unlocks the Parts resource and Scavenge for Parts activity.',
    maxLevel: 1,
    prerequisiteSkillId: 'scavenge_multiplier',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 0,
    positionY: 160,
    sortOrder: 2,
  },
  {
    skillId: 'parts_multiplier',
    name: 'Parts Multiplier',
    description: '+25% per level to Scavenge for Parts yield.',
    maxLevel: 4,
    prerequisiteSkillId: 'unlock_parts',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 220,
    positionY: 160,
    sortOrder: 3,
  },
  {
    skillId: 'unlock_metal',
    name: 'Unlock Metal',
    description: 'Unlocks the Metal resource and Scavenge for Metal activity.',
    maxLevel: 1,
    prerequisiteSkillId: 'unlock_parts',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 0,
    positionY: 320,
    sortOrder: 4,
  },
  {
    skillId: 'metal_multiplier',
    name: 'Metal Multiplier',
    description: '+25% per level to Scavenge for Metal yield.',
    maxLevel: 4,
    prerequisiteSkillId: 'unlock_metal',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 220,
    positionY: 320,
    sortOrder: 5,
  },
  {
    skillId: 'unlock_fabric',
    name: 'Unlock Fabric',
    description: 'Unlocks the Fabric resource and Scavenge for Fabric activity.',
    maxLevel: 1,
    prerequisiteSkillId: 'unlock_metal',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 0,
    positionY: 480,
    sortOrder: 6,
  },
  {
    skillId: 'fabric_multiplier',
    name: 'Fabric Multiplier',
    description: '+25% per level to Scavenge for Fabric yield.',
    maxLevel: 4,
    prerequisiteSkillId: 'unlock_fabric',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 220,
    positionY: 480,
    sortOrder: 7,
  },
  {
    skillId: 'unlock_food',
    name: 'Unlock Food',
    description: 'Unlocks the Food resource and Scavenge for Food activity.',
    maxLevel: 1,
    prerequisiteSkillId: 'unlock_fabric',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 0,
    positionY: 640,
    sortOrder: 8,
  },
  {
    skillId: 'food_multiplier',
    name: 'Food Multiplier',
    description: '+25% per level to Scavenge for Food yield.',
    maxLevel: 4,
    prerequisiteSkillId: 'unlock_food',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 220,
    positionY: 640,
    sortOrder: 9,
  },
  {
    skillId: 'unlock_medicine',
    name: 'Unlock Meds',
    description: 'Unlocks the Meds resource and Scavenge for Meds activity.',
    maxLevel: 1,
    prerequisiteSkillId: 'unlock_food',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 0,
    positionY: 800,
    sortOrder: 10,
  },
  {
    skillId: 'medicine_multiplier',
    name: 'Meds Multiplier',
    description: '+25% per level to Scavenge for Meds yield.',
    maxLevel: 4,
    prerequisiteSkillId: 'unlock_medicine',
    prerequisiteLevel: 1,
    prerequisitePlayerLevel: 0,
    costSkillPoints: 1,
    positionX: 220,
    positionY: 800,
    sortOrder: 11,
  },
  {
    skillId: 'unlock_classes',
    name: 'Unlock Classes',
    description:
      'Completes the tutorial tree. Additional class system placeholder.',
    maxLevel: 1,
    prerequisiteSkillId: 'medicine_multiplier',
    prerequisiteLevel: 4,
    prerequisitePlayerLevel: 30,
    costSkillPoints: 0,
    positionX: 500,
    positionY: 400,
    sortOrder: 12,
  },
];
