// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CoinSide,
} from "./types";


export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  anteScrap: __t.u64().name("ante_scrap"),
  roundNumber: __t.u32().name("round_number"),
  pot: __t.u64(),
  get result() {
    return __t.option(CoinSide);
  },
  revealedAt: __t.option(__t.timestamp()).name("revealed_at"),
});
