// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MinigameKind,
  MinigameSessionState,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  get kind() {
    return MinigameKind;
  },
  get state() {
    return MinigameSessionState;
  },
  hostUsername: __t.string().name("host_username"),
  minPlayers: __t.u8().name("min_players"),
  maxPlayers: __t.u8().name("max_players"),
  createdAt: __t.timestamp().name("created_at"),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
