// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().name("event_id"),
  username: __t.string(),
  structureId: __t.string().name("structure_id"),
  activityId: __t.string().name("activity_id"),
  resourceId: __t.string().name("resource_id"),
  amount: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
});
