// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  username: __t.string(),
  scrap: __t.u64(),
  xp: __t.u64(),
  playerLevel: __t.u32().name("player_level"),
  skillPoints: __t.u32().name("skill_points"),
  updatedAt: __t.timestamp().name("updated_at"),
});
