// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  invitationId: __t.u64().name("invitation_id"),
  groupId: __t.u64().name("group_id"),
  fromUsername: __t.string().name("from_username"),
  toUsername: __t.string().name("to_username"),
  createdAt: __t.timestamp().name("created_at"),
});
