// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  locationKey: __t.string().name("location_key"),
  name: __t.string(),
  icon: __t.string(),
  description: __t.string(),
  sortOrder: __t.u32().name("sort_order"),
  prerequisiteActivityId: __t.string().name("prerequisite_activity_id"),
  prerequisiteActivityUses: __t.u32().name("prerequisite_activity_uses"),
});
