// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  activityId: __t.string().name("activity_id"),
  name: __t.string(),
  description: __t.string(),
  icon: __t.string(),
  locationKey: __t.string().name("location_key"),
  kind: __t.string(),
  maxUses: __t.i32().name("max_uses"),
  prerequisiteSkillId: __t.string().name("prerequisite_skill_id"),
  prerequisiteSkillLevel: __t.u32().name("prerequisite_skill_level"),
  progressTarget: __t.u64().name("progress_target"),
  maxPerClick: __t.u64().name("max_per_click"),
  yieldResourceId: __t.string().name("yield_resource_id"),
  skillChainPrefix: __t.string().name("skill_chain_prefix"),
  sortOrder: __t.u32().name("sort_order"),
});
