// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  resourceId: __t.string().primaryKey().name("resource_id"),
  name: __t.string(),
  icon: __t.string(),
  unlockSkillId: __t.string().name("unlock_skill_id"),
  unlockSkillLevel: __t.u32().name("unlock_skill_level"),
  sortOrder: __t.u32().name("sort_order"),
});
