// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  skillId: __t.string().primaryKey().name("skill_id"),
  name: __t.string(),
  description: __t.string(),
  maxLevel: __t.u32().name("max_level"),
  prerequisiteSkillId: __t.string().name("prerequisite_skill_id"),
  prerequisiteLevel: __t.u32().name("prerequisite_level"),
  positionX: __t.i32().name("position_x"),
  positionY: __t.i32().name("position_y"),
  sortOrder: __t.u32().name("sort_order"),
});
