// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  upgradeId: __t.string().primaryKey().name("upgrade_id"),
  structureId: __t.string().name("structure_id"),
  name: __t.string(),
  description: __t.string(),
  kind: __t.string(),
  targetActivityId: __t.string().name("target_activity_id"),
  maxLevel: __t.u32().name("max_level"),
  costBase: __t.u64().name("cost_base"),
  costGrowthPer100: __t.u32().name("cost_growth_per_100"),
  yieldPerLevelPer100: __t.u32().name("yield_per_level_per_100"),
  sortOrder: __t.u32().name("sort_order"),
});
