// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  structureId: __t.string().primaryKey().name("structure_id"),
  name: __t.string(),
  description: __t.string(),
  icon: __t.string(),
  locationKey: __t.string().name("location_key"),
  buildActivityId: __t.string().name("build_activity_id"),
  sortOrder: __t.u32().name("sort_order"),
});
