// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import LoginReducer from "../login_reducer";
import LogoutReducer from "../logout_reducer";
import ScavengeReducer from "../scavenge_reducer";
import SignupReducer from "../signup_reducer";
import UpgradeScavengeReducer from "../upgrade_scavenge_reducer";

export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type ScavengeParams = __Infer<typeof ScavengeReducer>;
export type SignupParams = __Infer<typeof SignupReducer>;
export type UpgradeScavengeParams = __Infer<typeof UpgradeScavengeReducer>;

