// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptInvitationReducer from "../accept_invitation_reducer";
import AcceptMinigameInviteReducer from "../accept_minigame_invite_reducer";
import AdvanceBuildReducer from "../advance_build_reducer";
import CancelMinigameReducer from "../cancel_minigame_reducer";
import CdAttackReducer from "../cd_attack_reducer";
import CdEndTurnReducer from "../cd_end_turn_reducer";
import CdMulliganReducer from "../cd_mulligan_reducer";
import CdPlayCardReducer from "../cd_play_card_reducer";
import CfPickReducer from "../cf_pick_reducer";
import CfRevealReducer from "../cf_reveal_reducer";
import CheatAddLevelReducer from "../cheat_add_level_reducer";
import CheatAddScrapReducer from "../cheat_add_scrap_reducer";
import ClearSlotReducer from "../clear_slot_reducer";
import CreateGroupReducer from "../create_group_reducer";
import CreateMinigameReducer from "../create_minigame_reducer";
import DeclineInvitationReducer from "../decline_invitation_reducer";
import DeclineMinigameInviteReducer from "../decline_minigame_invite_reducer";
import InviteToGroupReducer from "../invite_to_group_reducer";
import InviteToMinigameReducer from "../invite_to_minigame_reducer";
import LeaveGroupReducer from "../leave_group_reducer";
import LeaveMinigameReducer from "../leave_minigame_reducer";
import LoginReducer from "../login_reducer";
import LogoutReducer from "../logout_reducer";
import RtTapReducer from "../rt_tap_reducer";
import ScavengeActivityReducer from "../scavenge_activity_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SetMinigameReadyReducer from "../set_minigame_ready_reducer";
import SignupReducer from "../signup_reducer";
import SlotActivityReducer from "../slot_activity_reducer";
import StartMinigameReducer from "../start_minigame_reducer";
import TravelToReducer from "../travel_to_reducer";
import UpgradeScavengeActivityReducer from "../upgrade_scavenge_activity_reducer";
import UpgradeSkillReducer from "../upgrade_skill_reducer";
import UpgradeStructureReducer from "../upgrade_structure_reducer";

export type AcceptInvitationParams = __Infer<typeof AcceptInvitationReducer>;
export type AcceptMinigameInviteParams = __Infer<typeof AcceptMinigameInviteReducer>;
export type AdvanceBuildParams = __Infer<typeof AdvanceBuildReducer>;
export type CancelMinigameParams = __Infer<typeof CancelMinigameReducer>;
export type CdAttackParams = __Infer<typeof CdAttackReducer>;
export type CdEndTurnParams = __Infer<typeof CdEndTurnReducer>;
export type CdMulliganParams = __Infer<typeof CdMulliganReducer>;
export type CdPlayCardParams = __Infer<typeof CdPlayCardReducer>;
export type CfPickParams = __Infer<typeof CfPickReducer>;
export type CfRevealParams = __Infer<typeof CfRevealReducer>;
export type CheatAddLevelParams = __Infer<typeof CheatAddLevelReducer>;
export type CheatAddScrapParams = __Infer<typeof CheatAddScrapReducer>;
export type ClearSlotParams = __Infer<typeof ClearSlotReducer>;
export type CreateGroupParams = __Infer<typeof CreateGroupReducer>;
export type CreateMinigameParams = __Infer<typeof CreateMinigameReducer>;
export type DeclineInvitationParams = __Infer<typeof DeclineInvitationReducer>;
export type DeclineMinigameInviteParams = __Infer<typeof DeclineMinigameInviteReducer>;
export type InviteToGroupParams = __Infer<typeof InviteToGroupReducer>;
export type InviteToMinigameParams = __Infer<typeof InviteToMinigameReducer>;
export type LeaveGroupParams = __Infer<typeof LeaveGroupReducer>;
export type LeaveMinigameParams = __Infer<typeof LeaveMinigameReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type RtTapParams = __Infer<typeof RtTapReducer>;
export type ScavengeActivityParams = __Infer<typeof ScavengeActivityReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SetMinigameReadyParams = __Infer<typeof SetMinigameReadyReducer>;
export type SignupParams = __Infer<typeof SignupReducer>;
export type SlotActivityParams = __Infer<typeof SlotActivityReducer>;
export type StartMinigameParams = __Infer<typeof StartMinigameReducer>;
export type TravelToParams = __Infer<typeof TravelToReducer>;
export type UpgradeScavengeActivityParams = __Infer<typeof UpgradeScavengeActivityReducer>;
export type UpgradeSkillParams = __Infer<typeof UpgradeSkillReducer>;
export type UpgradeStructureParams = __Infer<typeof UpgradeStructureReducer>;

