import { schema } from 'spacetimedb/server';
import {
  account,
  usernameDirectory,
  session,
  playerState,
  skillDefinition,
  skillPrerequisite,
  playerSkill,
  locationDefinition,
  activityDefinition,
  activityCost,
  resourceDefinition,
  playerResource,
  playerActivity,
  structureDefinition,
  structureUpgradeDefinition,
  playerStructure,
  playerStructureUpgrade,
  automationTick,
  automationEvent,
  group,
  groupMember,
  groupInvitation,
  groupContributionEvent,
  chatMessage,
  notification,
  tutorialStepDefinition,
  playerTutorialProgress,
} from './tables_core';
import {
  minigameSession,
  minigameMember,
  minigameInvite,
  minigamePrivateState,
  minigameResult,
  minigameTick,
  coinFlipGame,
  coinFlipBet,
  rhythmTapGame,
  rhythmTapNote,
  rhythmTapScore,
  cardDefinition,
  cardDuelBoard,
  cardDuelPlayer,
  cardDuelCardOnBoard,
} from './minigames/tables';

const spacetimedb = schema({
  account,
  usernameDirectory,
  session,
  playerState,
  skillDefinition,
  skillPrerequisite,
  playerSkill,
  locationDefinition,
  activityDefinition,
  activityCost,
  resourceDefinition,
  playerResource,
  playerActivity,
  structureDefinition,
  structureUpgradeDefinition,
  playerStructure,
  playerStructureUpgrade,
  automationTick,
  automationEvent,
  group,
  groupMember,
  groupInvitation,
  groupContributionEvent,
  chatMessage,
  notification,
  tutorialStepDefinition,
  playerTutorialProgress,
  minigameSession,
  minigameMember,
  minigameInvite,
  minigamePrivateState,
  minigameResult,
  minigameTick,
  coinFlipGame,
  coinFlipBet,
  rhythmTapGame,
  rhythmTapNote,
  rhythmTapScore,
  cardDefinition,
  cardDuelBoard,
  cardDuelPlayer,
  cardDuelCardOnBoard,
});

export default spacetimedb;
