import { schema } from 'spacetimedb/server';
import {
  account,
  usernameDirectory,
  session,
  playerState,
  skillDefinition,
  skillPrerequisite,
  playerSkill,
  locationDefinition,
  activityDefinition,
  activityCost,
  resourceDefinition,
  playerResource,
  playerActivity,
  structureDefinition,
  structureUpgradeDefinition,
  playerStructure,
  playerStructureUpgrade,
  automationTick,
  automationEvent,
  group,
  groupMember,
  groupInvitation,
  groupContributionEvent,
  chatMessage,
  notification,
  tutorialStepDefinition,
  playerTutorialProgress,
} from './tables_core';
import { statDefinition, playerStatSource } from './stats_tables';
import {
  skillTreeDefinition,
  skillPointPoolDefinition,
  playerSkillPointBalance,
  skillStatGrant,
} from './skill_tree_tables';
import {
  actionDefinition,
  actionStatScaling,
  playerKnownAction,
  playerActionLoadout,
} from './action_tables';
import {
  defensiveBattleSession,
  defensiveBattleParticipant,
  defensiveBattleStatSnapshot,
  defensiveBattleZombie,
  defensiveBattleHandSlot,
  defensiveBattleLog,
  defensiveBattleVoteCancelJob,
} from './battle_tables';
import {
  itemDefinition,
  itemDefinitionAffix,
  itemDefinitionRoll,
  itemInstance,
  itemInstanceAffix,
  equipmentSlotDefinition,
  craftingRecipe,
  craftingRecipeCost,
  armoryUpgradeCost,
  playerArmoryState,
  playerEquipment,
} from './armory_tables';
import {
  minigameSession,
  minigameMember,
  minigameInvite,
  minigamePrivateState,
  minigameResult,
  minigameTick,
  coinFlipGame,
  coinFlipBet,
  rhythmTapGame,
  rhythmTapNote,
  rhythmTapScore,
  cardDefinition,
  cardDuelBoard,
  cardDuelPlayer,
  cardDuelCardOnBoard,
} from './minigames/tables';

const spacetimedb = schema({
  account,
  usernameDirectory,
  session,
  playerState,
  skillDefinition,
  skillPrerequisite,
  playerSkill,
  locationDefinition,
  activityDefinition,
  activityCost,
  resourceDefinition,
  playerResource,
  playerActivity,
  structureDefinition,
  structureUpgradeDefinition,
  playerStructure,
  playerStructureUpgrade,
  automationTick,
  automationEvent,
  group,
  groupMember,
  groupInvitation,
  groupContributionEvent,
  chatMessage,
  notification,
  tutorialStepDefinition,
  playerTutorialProgress,
  statDefinition,
  playerStatSource,
  skillTreeDefinition,
  skillPointPoolDefinition,
  playerSkillPointBalance,
  skillStatGrant,
  actionDefinition,
  actionStatScaling,
  playerKnownAction,
  playerActionLoadout,
  defensiveBattleSession,
  defensiveBattleParticipant,
  defensiveBattleStatSnapshot,
  defensiveBattleZombie,
  defensiveBattleHandSlot,
  defensiveBattleLog,
  defensiveBattleVoteCancelJob,
  itemDefinition,
  itemDefinitionAffix,
  itemDefinitionRoll,
  itemInstance,
  itemInstanceAffix,
  equipmentSlotDefinition,
  craftingRecipe,
  craftingRecipeCost,
  armoryUpgradeCost,
  playerArmoryState,
  playerEquipment,
  minigameSession,
  minigameMember,
  minigameInvite,
  minigamePrivateState,
  minigameResult,
  minigameTick,
  coinFlipGame,
  coinFlipBet,
  rhythmTapGame,
  rhythmTapNote,
  rhythmTapScore,
  cardDefinition,
  cardDuelBoard,
  cardDuelPlayer,
  cardDuelCardOnBoard,
});

export default spacetimedb;
